services:
  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    env_file: ./.env
    networks:
      - inception
  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    env_file: ./.env
    networks:
      - inception
    ports:
      - 8080:9000 #This should be removed later on i just put it for testing since i still did not setup nginx

networks:
  inception:
    driver: bridge